### ISSUE TITLE
silly developer ergonomics request, warn on truthy COVERAGE=foo

### ISSUE THREAD

**Issue by efx** [kategengler/ember-cli-code-coverage#175]
I see truthy checks all over the place. 
As a developer, I read the documentation and saw `COVERAGE=true` and assumed I could just use `COVERAGE=1`. (Dangerous, and lazy). I then realized you must explicitly pass this value as a boolean or string: https://github.com/kategengler/ember-cli-code-coverage/blob/master/index.js#L242.

Could we add a warning if I or anyone else decides to pass in a truthy value that is not `true`? I propose the same kind of error ember-cli deprecations log.

**Comment by CvX** [comment]
I'd propose loosening that requirement and either just checking if env var is present at all, or inverting the current condition and checking if the var is not 'false' or '0'.

**Comment by kategengler** [comment]
I wouldn't want to loosen the requirement because I wouldn't want any builds to run with coverage/instrumentation that haven't thus far.

There's a bit of a gotcha to warning if it isn't an expected value, though, because this addon should only have console output or do anything in the case of the env var being true.

**Comment by abhilashlr** [comment]
@kategengler Do we need to add a warning message? I can work on a PR for this.

**Comment by rwwagner90** [comment]
I think this is a wontfix, as @kategengler said, it should not have output unless it's true.
