### ISSUE TITLE
No coverage report generated when used with @embroider/compat@^2.1.0

### ISSUE THREAD

**Issue by ArnaudWeyts** [kategengler/ember-cli-code-coverage#374]
- ember-cli version: `~4.8.0`
- ember-cli-code-coverage version: `2.0.0-beta-5`,
- @embroider/compat version: `2.1.0` and up
- @embroider/core version: `^2.1.1`
- @embroider/webpack version: `^2.1.1`

I've noticed that with starting from @embroider/compat@2.1.0, the code coverage report no longer gets generated. The test build still success, but nothing is outputted in the log and no `/coverage` folder is generated.

Once I downgrade `@embroider/compat@2.0.2`, everything seems to work again.

**Comment by AmauryD** [comment]
Same problem here. Nothing is generated when @embroider/compat is at version ~2.1.0.
 
When downgrading, the coverage folder is only generated when using `COVERAGE=true ember s` and then going to `http://localhost:4200/tests`.
Doing `COVERAGE=true ember test` does not generate the coverage folder.

Repro repository: https://github.com/TRIPTYK/ember-boilerplate .

**Comment by elidupuis** [comment]
Just ran into this issue as well after upgrading embroider to `2.1.1` and ember-cli-code-coverage to `2.0.0`. Reverting the embroider packages to `~2.0.2` appears to fix it for now.

Note that, for me, after reverting embroider everything is generated properly regardless of the command:

- `COVERAGE=true ember test`
- `COVERAGE=true ember test -s`
- `COVERAGE=true ember s` and using http://localhost:4200/tests

**Comment by tniezurawski** [comment]
Same here. I guess [the changelog](https://github.com/embroider-build/embroider/blob/main/CHANGELOG.md#embroidercompat-202---210) might help to understand where the issue came from:

![image](https://github.com/kategengler/ember-cli-code-coverage/assets/4335166/7a40ad71-b9a0-4630-9ca9-e35e59b556b2)

Does anything rings a bell to anyone?

**Comment by AmauryD** [comment]
After some digging in Embroider and Ember-cli-code-coverage, I found the problem.

The culprit is this line : https://github.com/embroider-build/embroider/blob/34fec6c15b65ed79a31b9ad9066b5b0004cd4876/packages/compat/src/default-pipeline.ts#L20

Internally, ember-cli-code-coverage uses [stableWorkspaceDir from @embroider/compat 0.x](https://github.com/kategengler/ember-cli-code-coverage/blob/23c661e11f4d37fe7bb899d2d5316482ae742be1/packages/ember-cli-code-coverage/index.js#L61) for getting the CWD generated by embroider. This method uses a md5 hash to get a semi-random project directory. But the method has changed in @embroider/compat 2.1.0 with a new environment parameter added to the hash. This mismatch in the function implementation will result in a wrong directory-guess from ember-cli-code-coverage. 

Maybe making @embroider/compat an optionalPeerDependency would have solved the problem. I will make a PR shortly.

**Comment by tniezurawski** [comment]
@AmauryD That makes sense! I had a feeling that hashing can play a role here.

btw I wanted to try your chance to confirm it works for me, but I am getting an error:

> COVERAGE=true ember test
Environment: test
cleaning up...
Cleanup error.
⠋ cleaning upCannot read properties of undefined (reading 'cleanup')
>
>
> Stack Trace and Error Report: /var/folders/d8/h8767lqn0jb3h53qj9v70_l80000gn/T/error.dump.4b81903fd3192063fd5d54a0eba84752.log
Cannot find module 'ember-cli-code-coverage'
Require stack:
> - /Users/PATH_TO_PROJECT/ember-cli-build.js

Do you know if I pointed to the fork in the wrong way or if that's something else? 🤔 (it's installing without problems)

> "ember-cli-code-coverage": "github:AmauryD/ember-cli-code-coverage#master",

**Comment by AmauryD** [comment]
I'm using     "ember-cli-code-coverage": "file:../amaury-ember-cli-code-coverage/packages/ember-cli-code-coverage" for testing. I think the github link does not work because the real package is in  `packages/ember-cli-code-coverage`.

**Comment by mansona** [comment]
Does https://github.com/kategengler/ember-cli-code-coverage/pull/379 fix this? Does anyone know? or is it not just because of a mismatch of embroider versions?
