### ISSUE TITLE
Take over the 'ember-cli-istanbul' package?

### ISSUE THREAD

**Issue by job13er** [kategengler/ember-cli-code-coverage#6]
Hey there, I happen to have parked the `ember-cli-istanbul` package in npm (having fully planned to implement it, but priorities shifted at work 😦 ) Would you like to take over ownership of that?

**Comment by sglanzer** [comment]
Interesting question, because if this is working well (and it appears to be) I'd be happy to deprecate the blanket integration in favor of this project, in which case using the `code-coverage` name would make it clear that this is the blessed addon.  

So I guess I would recommend taking over the Istanbul name if there is value in that name association (clearer than code-coverage? Probably not) or if there is value in supporting multiple coverage tools (I don't believe there is)

**Comment by rwjblue** [comment]
I agree with @sglanzer here. I think it makes sense to have a good general solution to "how do I get code coverage numbers", and I think this library is positioned well as that solution.

**Comment by job13er** [comment]
Interesting. That didn't seem like the way other addons were named. It's not `ember-cli-testing` but rather `ember-cli-qunit` and `ember-cli-mocha`, is the distinction here because no one *should* want to use anything but `istanbul` for coverage since it's not something you actually interface with?

**Comment by sglanzer** [comment]
Blanket isn't really maintained and I personally don't see a need to support multiple coverage tools, so as long as there is a community solution to this then it's fine that it's the only game in town and the name can support that.  If there was a feature difference in the coverage tools then I'd stick with `istanbal` and `blanket`, but I don't believe that's the case.
