### ISSUE TITLE
Include support in options for paths/files to include

### ISSUE THREAD

**Issue by fushi** [kategengler/ember-cli-code-coverage#91]
This is actually a more generic way to solve #86 - Allow us to add paths to include, rather than just paths to exclude.

**Comment by kategengler** [comment]
I think you could make this work with a change here https://github.com/kategengler/ember-cli-code-coverage/blob/master/index.js#L90 to check for the file inside engines in addition to inside app. I'm not sure how engines end up looking in the app tree though.  That code's purpose is to make sure the file isn't from an addon's app/ that gets merged in.

**Comment by rwwagner90** [comment]
@adamjmcgrath do we support passing includes and excludes?

**Comment by adamjmcgrath** [comment]
We don't support `includes` - it would be difficult to repatriate the coverage back to the file that was covered if the user wanted to include files from say their `vendor` folder.

We do support `excludes` but you still need to specify the path to the module (`my-app-name/app.js`) rather than the path to the file on your file system (`app/app.js`).

**Comment by rwwagner90** [comment]
@adamjmcgrath I tend to agree. I think the underlying issue is people were not getting coverage for an in-repo engine. I'll add tests for in-repo engines and get that squared away.
