### ISSUE TITLE
Question: option to fail a build if coverage result is below a given percentage?

### ISSUE THREAD

**Issue by pixelhandler** [kategengler/ember-cli-code-coverage#95]
Thanks so much for providing this addon? I enjoyed using blanket as well. I recall there was an option to fail a build if the coverage result was below a given value.

Does ember-cli-code-coverage have an option to fail an ember build when the coverage result is below a given percentage value?

**Comment by rwjblue** [comment]
No there is nothing like that at the moment.  I'm not sure if it belongs here directly, or via another addon...

**Comment by pixelhandler** [comment]
@rwjblue thank you sir!

**Comment by job13er** [comment]
@pixelhandler just as an FYI: [pr-bumper](https://github.com/ciena-blueplanet/pr-bumper) has a mechanism for comparing the current coverage against a saved baseline in `package.json` which will then be updated when the PR is merged. The `pr-bumper check-coverage` command will fail if the coverage dropped, so that might help.
